require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe EventSuggestionsController, :type => :controller do
  include Devise::TestHelpers

  let(:user) { create :user }
  # This should return the minimal set of attributes required to create a valid
  # EventSuggestion. As you add validations to EventSuggestion, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    {  starts_at_date:'2020-08-23',
       ends_at_date:'2020-08-23',
       starts_at_time:'17:00',
       ends_at_time:'23:59',
       user_id: user.id
    }
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # EventSuggestionsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  before(:each) do
    @request.env["devise.mapping"] = Devise.mappings[:user]
    sign_in user
  end
  
  describe "GET index" do
    it "assigns all event_suggestions as @event_suggestions" do
      event_suggestion = EventSuggestion.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:event_suggestions)).to eq([event_suggestion])
    end
  end

  describe "GET show" do
    it "assigns the requested event_suggestion as @event_suggestion" do
      event_suggestion = EventSuggestion.create! valid_attributes
      get :show, {:id => event_suggestion.to_param}, valid_session
      expect(assigns(:event_suggestion)).to eq(event_suggestion)
    end
  end

  describe "GET new" do
    it "assigns a new event_suggestion as @event_suggestion" do
      get :new, {}, valid_session
      expect(assigns(:event_suggestion)).to be_a_new(EventSuggestion)
    end
  end

  describe "GET edit" do
    it "assigns the requested event_suggestion as @event_suggestion" do
      event_suggestion = EventSuggestion.create! valid_attributes
      get :edit, {:id => event_suggestion.to_param}, valid_session
      expect(assigns(:event_suggestion)).to eq(event_suggestion)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new EventSuggestion" do
        expect {
          post :create, {:event_suggestion => valid_attributes}, valid_session
        }.to change(EventSuggestion, :count).by(1)
      end

      it "assigns a newly created event_suggestion as @event_suggestion" do
        post :create, {:event_suggestion => valid_attributes}, valid_session
        expect(assigns(:event_suggestion)).to be_a(EventSuggestion)
        expect(assigns(:event_suggestion)).to be_persisted
      end

      it "redirects to the created event_suggestion" do
        post :create, {:event_suggestion => valid_attributes}, valid_session
        expect(response).to redirect_to(EventSuggestion.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved event_suggestion as @event_suggestion" do
        post :create, {:event_suggestion => invalid_attributes}, valid_session
        expect(assigns(:event_suggestion)).to be_a_new(EventSuggestion)
      end

      it "re-renders the 'new' template" do
        post :create, {:event_suggestion => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested event_suggestion" do
        event_suggestion = EventSuggestion.create! valid_attributes
        put :update, {:id => event_suggestion.to_param, :event_suggestion => new_attributes}, valid_session
        event_suggestion.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested event_suggestion as @event_suggestion" do
        event_suggestion = EventSuggestion.create! valid_attributes
        put :update, {:id => event_suggestion.to_param, :event_suggestion => valid_attributes}, valid_session
        expect(assigns(:event_suggestion)).to eq(event_suggestion)
      end

      it "redirects to the event_suggestion" do
        event_suggestion = EventSuggestion.create! valid_attributes
        put :update, {:id => event_suggestion.to_param, :event_suggestion => valid_attributes}, valid_session
        expect(response).to redirect_to(event_suggestion)
      end
    end

    describe "with invalid params" do
      it "assigns the event_suggestion as @event_suggestion" do
        event_suggestion = EventSuggestion.create! valid_attributes
        put :update, {:id => event_suggestion.to_param, :event_suggestion => invalid_attributes}, valid_session
        expect(assigns(:event_suggestion)).to eq(event_suggestion)
      end

      it "re-renders the 'edit' template" do
        event_suggestion = EventSuggestion.create! valid_attributes
        put :update, {:id => event_suggestion.to_param, :event_suggestion => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested event_suggestion" do
      event_suggestion = EventSuggestion.create! valid_attributes
      expect {
        delete :destroy, {:id => event_suggestion.to_param}, valid_session
      }.to change(EventSuggestion, :count).by(-1)
    end

    it "redirects to the event_suggestions list" do
      event_suggestion = EventSuggestion.create! valid_attributes
      delete :destroy, {:id => event_suggestion.to_param}, valid_session
      expect(response).to redirect_to(event_suggestions_url)
    end
  end

end
